# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: First

steps:
- script: terraform apply git@github.com:LutsenkoVO/Learn/main.tf

